# Generated by Django 4.0 on 2021-12-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('avg_price', models.FloatField()),
                ('std_deviation', models.FloatField()),
            ],
        ),
    ]
