# Generated by Django 4.0 on 2022-01-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0004_alter_ville_std_deviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=100, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
                ('mail_destinataire', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
