# Generated by Django 4.0 on 2021-12-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_lot', models.CharField(max_length=100)),
                ('nb_piece', models.FloatField(blank=True, null=True)),
                ('typologie', models.CharField(max_length=100)),
                ('prix_tva_reduite', models.FloatField(blank=True, null=True)),
                ('prix_tva_normale', models.FloatField(blank=True, null=True)),
                ('prix_HT', models.FloatField(blank=True, null=True)),
                ('prix_m2_HT', models.FloatField(blank=True, null=True)),
                ('prix_m2_TTC', models.FloatField(blank=True, null=True)),
                ('surface', models.IntegerField(blank=True)),
                ('etage', models.CharField(blank=True, max_length=10, null=True)),
                ('orientation', models.CharField(max_length=100)),
                ('exterieur', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('parking', models.IntegerField(default=0)),
                ('nom_programme', models.CharField(blank=True, max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
                ('date_fin_programme', models.CharField(max_length=100)),
                ('adresse_entiere', models.CharField(max_length=100)),
                ('promoteur', models.CharField(blank=True, max_length=100)),
                ('date_extraction', models.CharField(max_length=100)),
            ],
        ),
    ]
